---
version: "3"

services:
  armory-fortress:
    container_name: armory
    image: twosixarmory/fortress:latest

    build:
     context: .
     dockerfile: ./docker/Dockerfile-base

    # command: ['ipython']

    ports:
      - 8888:8888

    volumes:
      - ./environment.yml:/app/environment.yml
      - ./:/workspace/app
      # - ./notebooks:/workspace/notebooks

    stdin_open: true
    tty: true


  # armory-launcher:  # Spawns containers using host daemon
  # armory-database:  # Stores training data for whitebox models and tar'd blackbox models

######
# NOTES
#  o Overview
#     - armory-fortress container is the main container that runs the Armory
#     - armory-launcher container is used to spawn containers using the host daemon
#     - armory-database container is used to store training data for whitebox models and tar'd blackbox models
#
#  o Best method for handling data...
#     - armory-fortress container mounts a volume to the host machine
#     - model zoo?
#       * https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md
#     - training data + instructions for training?
#
# mkdir -p workspace/{app,data,logs,lib,plugins}
#
# docker-compose --file docker-compose.yml up -d --build armory-fortress
# docker-compose exec armory /bin/bash
######
