---
version: "3"
services:
  armory-datasets:
    container_name: armory-datasets
    image: twosixarmory/pytorch:0.16.0
    # command: ["tail", "-f", "/dev/null"]
    # entrypoint: [ "/bin/bash" ]
    ports:
      - 53:53
      - 443:443
      - 8888:8888
    volumes:
      - ./armory:/armory-repo/armory:z
      - ./pyproject.toml:/armory-repo/pyproject.toml:z
      - ./workspace:/workspace:z
      - ./tools/datasets/entrypoint.sh:/tmp/entrypoint.sh:z

    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: [gpu]
    # tty: true
    stdin_open: true
