---
version: "3"
services:
  armory-launcher:
    container_name: armory-launcher
    hostname: armory-launcher

    image: twosixarmory/pytorch:latest

    # command: ["tail", "-f", "/dev/null"]
    # entrypoint: [ "/bin/bash" ]

    networks:
      armory_network:
        aliases:
          - armory-launcher

    ports:
      - 8888:8888

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw

      - ./tmp/entrypoint.sh:/tmp/entrypoint.sh:z
      - ./tmp/docker.management.patch:/tmp/docker.management.patch:z

      - ./data/:/workspace/data/:z

      - ./notebooks/:/workspace/notebooks/:z

      - ./tmp/config.json:/root/.armory/config.json:z

      - ./armory/scenario_configs/:/workspace/scenarios/:z

      - ./armory:/armory-repo/:z
      # - ./armory:/workspace/src/:z

    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: [gpu]

    # tty: true
    stdin_open: true


networks:
  armory_network:
    driver: bridge
