from __future__ import annotations

import os
import platform
import subprocess
import sys
from contextlib import contextmanager
from tempfile import TemporaryDirectory

import pathspec
from hatchling.builders.hooks.plugin.interface import BuildHookInterface


class BuildEnviroment(BuildHookInterface):
  PLUGIN_NAME = 'build-enviroment'

  def __init__(self):
    print("Build Enviroment Hook Executing...")
    ...


"""
__about__.py
THIS FILE IS AUTOMATICALLY GENERATED - Do Not Modify Below This Line
#############################################################################
APP_NAME = "armory"
VCS_VERSION = '1.1.1-dev'
GITHUB_URL = 'github.com/twosixlabs/armory'
"""
