ARG base_image_tag

FROM twosixarmory/base:${base_image_tag} AS armory-local

WORKDIR /armory-repo

RUN echo "Updating pip" && \
    pip install --upgrade pip && \
    echo "Building ART" && \
    pip install --no-cache-dir \
    adversarial-robustness-toolbox==1.12.1

RUN git clone https://github.com/ifzhang/ByteTrack.git && \
    cd ByteTrack  && \
    pip3 install -r requirements.txt  && \
    python3 setup.py develop  && \
    pip3 install cython; pip3 install 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI' && \
    pip3 install cython_bbox

# NOTE: This COPY command is filtered using the `.dockerignore` file
#       in the root of the repo.
COPY ./ /armory-repo

RUN echo "Building Armory from local source" && \
    pip install --no-compile --no-cache-dir --editable . && \
    echo "Configuring Armory..." && \
    armory configure --use-default && \
    echo "Cleaning up..." && \
    rm -rf /armory-repo/.git

WORKDIR /workspace
