ARG BASE_IMAGE="ubuntu"
ARG RELEASE_TAG="22.04"

ARG MINICONDA_URL="https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"


FROM ${BASE_IMAGE}:${RELEASE_TAG}

LABEL armory.client=development


ENV \
  DEBIAN_FRONTEND="noninteractive" \
  PYTHON_VERSION="3.8" \
  TZ="UTC" \
  LC_ALL="en_US.UTF-8" \
  LANG="en_US.UTF-8" \
  LANGUAGE="en_US:en" \
  USER="armory" \
  PASSWORD="armory"

USER root


# Install ubuntu packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        git \
        curl \
        ca-certificates \
        sudo \
        locales \
        openssh-server \
        vim && \
    # Remove the effect of `apt-get update`
    rm -rf /var/lib/apt/lists/* && \
    # Generate and Set locals
    sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
      locale-gen && \
      dpkg-reconfigure --frontend=noninteractive locales && \
      update-locale LANG=${LANG} && \
    # Setup timezone
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
    # Fix execution permissions
    chmod -R a+rwx /usr/local/bin/ && \
    chmod 644 /etc/resolv.conf && \
    # Configure dynamic linker run-time bindings
    ldconfig
    # Cleanup
    #clean-layer.sh


RUN \
  useradd \
    --password '' \
    --system \
    --create-home \
    --home-dir /home/${USER} \
    --groups sudo \
    --gid 0 \
    --uid 1000 \
    --shell /bin/bash \
    ${USER} \
  && \
    echo "${USER} ALL=(ALL) NOPASSWD:ALL" > "/etc/sudoers.d/90-${USER}" && \
    usermod -aG sudo ${USER}

ENV HOME="/home/${USER}"
WORKDIR $HOME


# Install miniconda
# Referenced PyTorch's Dockerfile:
#   https://github.com/pytorch/pytorch/blob/master/docker/pytorch/Dockerfile
RUN curl -o miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    chmod +x miniconda.sh && \
    ./miniconda.sh -b -p conda && \
    rm miniconda.sh && \
    conda/bin/conda install -y python=$PYTHON_VERSION jupyter jupyterlab

ENV PATH $HOME/conda/bin:$PATH

RUN touch $HOME/.bashrc && \
    echo "export PATH=$HOME/conda/bin:$PATH" >> $HOME/.bashrc


# Port 8888 for JupyterLab
EXPOSE 8888
# EXPOSE 22


USER ${USER}

RUN mkdir "${HOME}/app/"
VOLUME [ "${HOME}/app/" ]


# Jupyter config
# /home/armory/.jupyter/jupyter_notebook_config.py

ENTRYPOINT [ \
  "jupyter", "notebook", \
    "--ip=0.0.0.0", \
    "--port=8888", \
    "--NotebookApp.token=''", \
    "--NotebookApp.password=''", \
    "--no-browser", \
    "--notebook-dir=app" \
    # "--config=${HOME}/.jupyter/config.py", \
    # --sock=<Unicode>
]

