#!/usr/bin/env docker
---

version: '3'
services:
  armory-gpu:
    image: armory-gpu/testing:latest
    # build:
    #  context: .
    #  dockerfile: Dockerfile-GPU
    container_name: armory-gpu
    expose:
      - "9999"
    ports:
      - 9999:9999
    volumes:
      - ./server-resources:/armory/resources
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    networks:
      - armory-net


  armory-client:
    image: armory-client/testing:latest
    # env_file:
    #   - client-resources/client-variables.env
    # build:
    #  context: .
    #  dockerfile: Dockerfile-Client
    container_name: armory-client
    privileged: true
    restart: unless-stopped
    expose:
      - "8888"
    ports:
      - 8888:8888
    volumes:
      - ./client-resources/app:/home/armory/app/
    #   - ${CERT_PATH?err}:/opt/app/keystore.p12:Z
    environment:
      - JUPYTER_IP=0.0.0.0
      - JUPYTER_PORT=8888
    networks:
      - armory-net

networks:
  armory-net: