name: armory
dependencies:
  - conda-forge::cudatoolkit=11.3.1
  - python=3.9.*
  - pip
  - pytorch::pytorch=1.12.1=py3.9_cuda11.3_cudnn8.3.2_0
  - pytorch::torchvision=0.13.1=py39_cu113
  - scipy==1.8.1
  - numpy==1.22.4
  - pillow
  - ffmpeg
  - tqdm
  - tensorflow==2.9.1
  - keras==2.9.0
  - matplotlib==3.5.2
  - scikit-learn==1.1.2
  - six==1.15.0
  - Pillow==9.2.0
  - pytest-cov==3.0.0
  - tqdm==4.64.0
  - statsmodels==0.13.2
  - pydub==0.25.1
  - resampy==0.3.1
  - ffmpeg-python==0.2.0
  - cma==3.2.2
  - pandas==1.4.3
  - h5py==3.7.0
  - tensorflow-addons==0.17.1
  - mxnet==1.6.0
  - torch==1.12.0
  - torchaudio==0.12.0
  - torchvision==0.13.0
  - catboost==1.0.6
  - GPy==1.10.0
  - lightgbm==3.3.2
  - xgboost==1.6.1
  - kornia==0.6.6
  - lief==0.12.1
  - pytest==7.1.2
  - pytest-pep8==1.0.6
  - pytest-mock==3.8.2
  - codecov==2.1.12
  - requests==2.28.


    #  conda install -y --update-all \
    #         'python='$PYTHON_VERSION \
    #         'ipython=7.24.*' \
    #         'notebook=6.4.*' \
    #         'jupyterlab=3.0.*' \
    #         # TODO: nbconvert 6.x makes problems with template_path
    #         'nbconvert=5.6.*' \
    #         # TODO: temp fix: yarl version 1.5 is required for lots of libraries.
    #         'yarl==1.5.*' \
    #         # TODO install scipy, numpy, sklearn, and numexpr via conda for mkl optimizaed versions: https://docs.anaconda.com/mkl-optimizations/
    #         'scipy==1.7.*' \
    #         'numpy==1.19.*' \
    #         scikit-learn \
    #         numexpr && \


  # ResolvePackageNotFound:
  # - pytorch::torchvision[version='0.13.0,==0.13.1',build=py39_cu113]
  # - lief==0.12.1
  # - cma==3.2.2
  # - codecov==2.1.12
  # - torch==1.12.0
  # - mxnet==1.6.0c