---

# TODO:
# scenario:
#   name: <string>
#   description: <string>
#   version: <string>
scenario:
  _description: Baseline cifar10 image classification
  adhoc: null
  attack:
    knowledge: white
    kwargs:
      batch_size: 1
      eps: 0.031
      eps_step: 0.007
      max_iter: 20
      num_random_init: 1
      random_eps: false
      targeted: false
      verbose: false
    module: art.attacks.evasion
    name: ProjectedGradientDescent
    use_label: true
  dataset:
    batch_size: 64
    framework: numpy
    module: armory.data.datasets
    name: cifar10
  defense: null
  metric:
    means: true
    perturbation: linf
    record_metric_per_sample: false
    task:
    - categorical_accuracy
  model:
    fit: true
    fit_kwargs:
      nb_epochs: 20
    model_kwargs: {}
    module: armory.baseline_models.pytorch.cifar
    name: get_art_model
    weights_file: null
    wrapper_kwargs: {}
  scenario:
    kwargs: {}
    module: armory.scenarios.image_classification
    name: ImageClassificationTask
