---
# yamllint disable
name: 🤖 Docker Tests

on: workflow_call

env:
  DOCKER_BUILDKIT: 1

# TODO: Add independent job that builds the images.
jobs:
  docker-torch-unit:
    name: ☁️ Docker Pytorch Image Tests
    runs-on: ubuntu-latest
    steps:
      - name: 🤞 Run Image tests
        run: |
          echo "TESTING"
