---
name: 🤖 Docker Tests

on: workflow_call

env:
  DOCKER_BUILDKIT: 1

jobs:
  docker-torch-unit:
    name: ☁️ Docker Fortress Image Tests
    runs-on: ubuntu-latest
    steps:
      - name: 🐄 checkout armory full depth with tags for scm
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🐍 Use Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: ⚙️ Install Armory
        shell: bash
        run: |
          python -m pip install --upgrade pip build
          pip install .
          armory configure --use-defaults

      - name: 🚧 Build the Container
        run: |
          make image

      # TODO: Create/mount a volume with the tests and config files.
      # yamllint disable rule:indentation
      - name: 📐 Run Unit Tests
        run: |
          IMAGE_VERSION=`armory --show-docker-version-tag`
          docker run                                  \
            --rm                                      \
            --workdir /armory-repo                    \
            twosixarmory/fortress:${IMAGE_VERSION}    \
              pytest                                  \
                -c /armory-repo/pyproject.toml        \
                -m "not docker_required and unit"     \
                ./tests/

      - name: 📢 Run Deep Speech Tests
        run: |
          IMAGE_VERSION=`armory --show-docker-version-tag`
          docker run                              \
          --rm                                    \
          --workdir /armory-repo                  \
          twosixarmory/fortress:${IMAGE_VERSION}  \
            pytest                                \
              -c /armory-repo/pyproject.toml      \
              -m "pytorch_deepspeech"             \
              ./tests/
      # yamllint enable rule:indentation
