---
name: 🐛📦 Build & Test

on:
  workflow_dispatch:
    # inputs:
    #   test-run:
    #     type: choice
    #     description: CI Workflow to Execute
    #     options:
    #       - Q & A Test
    #       - Stand Alone Test
    #       - Docker Test
    #       - All Tests
    # TODO: Use menu for dispatching workflows
    #  >>> if: github.event.inputs.test-run == 'All Tests' || github.event.inputs.test-run == 'Q & A Test'

  push:
    branches:
      - master
      - develop
      - 'v[0-9]+.[0-9]+.[0-9]+'  # release branches have the form v1.9.x
      - 'rc[0-9]+.[0-9]+.[0-9]+'  # release candidate branches

  pull_request:
    branches:
      - master
      - develop
    # types:
    #   - opened
    #   - reopened
    #   - synchronize
    #   - ready_for_review


env:
  DOCKER_BUILDKIT: 1


jobs:
  scan-lint-build:
    uses: ./.github/workflows/1-scan-lint-build.yml

  test-stand-alone-builds:
    needs: scan-lint-build
    uses: ./.github/workflows/2-test-stand-alone.yml

  test-docker-builds:
    uses: ./.github/workflows/3-test-docker.yml
