---
name: 🎁 Armory Release Workflow

on:
  repository_dispatch:
    types: build-and-release

  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        description: Execute a dry-run(no uploads) of the workflow
        required: true
        default: true

# Limit workflow to one job per branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RELEASE_DRY_RUN: "${{ github.event_name != 'repository_dispatch' && github.event.inputs.dry_run }}"

jobs:
  release-wheel:
    name: 🛞 Build release wheel
    runs-on: ubuntu-latest
    steps:
      - name: 🐍 Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: 📩 Checkout Armory w/ full depth(for tags and SCM)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.client_payload.branch }}

      - name: 🔨 Build wheel
        run: |
          pip install pip==22.2.2
          pip install hatch
          hatch build --clean --target wheel

      # TODO: Add pre-release steps; e.g. publish to TestPyPI
      - name: 🐦 Release wheel
        if: ${{ env.RELEASE_DRY_RUN == 'false' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.pypi_token }}
          packages_dir: dist
          verbose: true

      - name: 📁 Archiving Artifacts
        uses: actions/upload-artifact@v3
        if: ${{ !failure() }}
        continue-on-error: true
        with:
          name: armory-release-artifacts
          retention-days: 1
          path: |
            dist/*.whl


  release-docker:
    name: Build and Release Docker Images
    needs: [release-wheel]
    runs-on: ubuntu-latest

    steps:
      - name: 🐍 Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: 📩 Checkout Armory w/ full depth(for tags and SCM)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.client_payload.branch }}

      - name: 🌎 Setup Build Environment
        run: |
          pip install pip>=22.2.2
          pip install .

          armory configure --use-defaults

          ARMORY_VERSION=`python -m armory --version 2> /dev/null | sed -r 's/\+/\./g'`
          echo "ARMORY_VERSION=${ARMORY_VERSION}" >> $GITHUB_ENV

      - name: ☁️ Login to DockerHub
        if: ${{ env.RELEASE_DRY_RUN == 'false' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🔨 Build Release Image
        run: |
          echo "Armory Version: ${{ env.ARMORY_VERSION }}"
          bash docker/build.sh

      - name: 📁 Archiving Artifacts
        uses: actions/upload-artifact@v3
        if: ${{ !failure() }}
        continue-on-error: true
        with:
          name: armory-release-artifacts
          retention-days: 1
          path: |
            /tmp/build.log

      - name: 📦 Push Release Images
        if: ${{ env.RELEASE_DRY_RUN == 'false' }}
        run: |
          ARMORY_VERSION="${{ env.ARMORY_VERSION }}"

          echo "Pushing twosixarmory/armory:${ARMORY_VERSION}"
          docker push twosixarmory/armory:${ARMORY_VERSION}

          echo "Tagging twosixarmory/armory:${ARMORY_VERSION} as twosixarmory/armory:latest"
          docker tag twosixarmory/armory:${ARMORY_VERSION} twosixarmory/armory:latest

          echo "Pushing ${{ matrix.image }}:latest"
          docker push twosixarmory/armory:latest


# Workflow Test:
# act --detect-event -j release-wheel
# act workflow_dispatch -j release-docker --eventpath .github/workflows/tests/release-dry-run.json
